2024-07-30 17:01:07 | ERROR | stderr | [rank0]: Traceback (most recent call last):
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "<frozen runpy>", line 88, in _run_code
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "/home/aac/kai/repository/ADAR-MED/fastchat/serve/vllm_worker.py", line 290, in <module>
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:     engine = AsyncLLMEngine.from_engine_args(engine_args)
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "/home/aac/anaconda3/envs/kai_vllm/lib/python3.11/site-packages/vllm-0.4.2+rocm614-py3.11-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 388, in from_engine_args
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:     engine = cls(
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:              ^^^^
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "/home/aac/anaconda3/envs/kai_vllm/lib/python3.11/site-packages/vllm-0.4.2+rocm614-py3.11-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 342, in __init__
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:     self.engine = self._init_engine(*args, **kwargs)
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "/home/aac/anaconda3/envs/kai_vllm/lib/python3.11/site-packages/vllm-0.4.2+rocm614-py3.11-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 464, in _init_engine
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:     return engine_class(*args, **kwargs)
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "/home/aac/anaconda3/envs/kai_vllm/lib/python3.11/site-packages/vllm-0.4.2+rocm614-py3.11-linux-x86_64.egg/vllm/engine/llm_engine.py", line 222, in __init__
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:     self.model_executor = executor_class(
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:                           ^^^^^^^^^^^^^^^
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "/home/aac/anaconda3/envs/kai_vllm/lib/python3.11/site-packages/vllm-0.4.2+rocm614-py3.11-linux-x86_64.egg/vllm/executor/executor_base.py", line 41, in __init__
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:     self._init_executor()
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "/home/aac/anaconda3/envs/kai_vllm/lib/python3.11/site-packages/vllm-0.4.2+rocm614-py3.11-linux-x86_64.egg/vllm/executor/gpu_executor.py", line 24, in _init_executor
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:     self.driver_worker.load_model()
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "/home/aac/anaconda3/envs/kai_vllm/lib/python3.11/site-packages/vllm-0.4.2+rocm614-py3.11-linux-x86_64.egg/vllm/worker/worker.py", line 121, in load_model
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:     self.model_runner.load_model()
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "/home/aac/anaconda3/envs/kai_vllm/lib/python3.11/site-packages/vllm-0.4.2+rocm614-py3.11-linux-x86_64.egg/vllm/worker/model_runner.py", line 134, in load_model
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:     self.model = get_model(
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:                  ^^^^^^^^^^
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "/home/aac/anaconda3/envs/kai_vllm/lib/python3.11/site-packages/vllm-0.4.2+rocm614-py3.11-linux-x86_64.egg/vllm/model_executor/model_loader/__init__.py", line 21, in get_model
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:     return loader.load_model(model_config=model_config,
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "/home/aac/anaconda3/envs/kai_vllm/lib/python3.11/site-packages/vllm-0.4.2+rocm614-py3.11-linux-x86_64.egg/vllm/model_executor/model_loader/loader.py", line 243, in load_model
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:     model.load_weights(
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "/home/aac/anaconda3/envs/kai_vllm/lib/python3.11/site-packages/vllm-0.4.2+rocm614-py3.11-linux-x86_64.egg/vllm/model_executor/models/llama.py", line 408, in load_weights
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:     weight_loader(param, loaded_weight, shard_id)
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:   File "/home/aac/anaconda3/envs/kai_vllm/lib/python3.11/site-packages/vllm-0.4.2+rocm614-py3.11-linux-x86_64.egg/vllm/model_executor/layers/linear.py", line 458, in weight_loader
2024-07-30 17:01:07 | ERROR | stderr | [rank0]:     param_data.copy_(loaded_weight)
2024-07-30 17:01:07 | ERROR | stderr | [rank0]: KeyboardInterrupt
